### ISSUE TITLE
[emoji] should not used on @keyframes

### ISSUE THREAD

**Issue by Maorey** [webpack/loader-utils#149]
Name parameter `[folder]__[name]_[local][emoji]`:

``` scss
.array {
  padding: 6px;
  display: inline-block;
  border: solid $colorHighlight;
  border-width: 0 2px 2px 0;
  animation: float 1s infinite ease-out;

  @keyframes float {
    0% {
      transform: rotate(-135deg) translate3d(-5px, -5px, 0);
    }
    100% {
      transform: rotate(-135deg) translate3d(5px, 5px, 0);
    }
  }
}
```
Result:

``` css
.index__App_array\1F5BC {
  padding: 6px;
  display: inline-block;
  border: solid #2588df;
  border-width: 0 2px 2px 0;
  -webkit-animation: index__app_float\1F3D3 1s infinite ease-out;
  animation: index__app_float\1F3D3 1s infinite ease-out;
}
@-webkit-keyframes index__App_float\1F3D3 {
  0% {
    -webkit-transform: rotate(-135deg) translate3d(-5px, -5px, 0);
    transform: rotate(-135deg) translate3d(-5px, -5px, 0);
  }
  100% {
    -webkit-transform: rotate(-135deg) translate3d(5px, 5px, 0);
    transform: rotate(-135deg) translate3d(5px, 5px, 0);
  }
}
@keyframes index__App_float\1F3D3 {
  0% {
    -webkit-transform: rotate(-135deg) translate3d(-5px, -5px, 0);
    transform: rotate(-135deg) translate3d(-5px, -5px, 0);
  }
  100% {
    -webkit-transform: rotate(-135deg) translate3d(5px, 5px, 0);
    transform: rotate(-135deg) translate3d(5px, 5px, 0);
  }
}
```

Animation does not work unless you remove `\1F3D3`
