### ISSUE TITLE
Add query token 

### ISSUE THREAD

**Issue by renarsvilnis** [webpack/loader-utils#40]
### Issue

At work we came across a problem with loading web-fonts. For some browsers, such as `<IE8` there needs to be  a query string in the file url `?#iefix`, otherwise it does not parse the font file 😓 [[source](https://github.com/CSSLint/csslint/wiki/Bulletproof-font-face)].

``` css
@font-face {
  font-family: 'MyFontFamily';
  src: url('./myfont-webfont.eot?#iefix') format('embedded-opentype'), 
     url('./myfont-webfont.woff') format('woff'), 
     url('./myfont-webfont.ttf') format('truetype'),
     url('./myfont-webfont.svg#svgFontName') format('svg');
}
```

[Webpack loader documentation states that there is an `this.resourceQuery` property inside of the loader context.](http://webpack.github.io/docs/loaders.html#resourcequery) But didn't find `loader-utils` using it anywhere.
### Suggestion

My suggestion is to add a new token `[query]`, that is the `this.resourceQuery` including `?` symbol.
### Examples

```
// loaderContext.resourcePath = '/myfont-webfont.eot?#iefix'
loaderUtils.interpolateName(loaderContext, '[path][name].[ext]', { content: ... });
// => './myfont-webfont.eot'

// loaderContext.resourcePath = '/myfont-webfont.eot?#iefix'
loaderUtils.interpolateName(loaderContext, '[path][name].[ext][query]', { content: ... });
// => './myfont-webfont.eot?#iefix'

// loaderContext.resourcePath = '/myfont-webfont.eot?#iefix'
loaderUtils.interpolateName(loaderContext, '[path][name].[ext]?[hash]', { content: ... });
// => './myfont-webfont.eot?9473fdd0d880a43c21b7778d34872157'

// loaderContext.resourcePath = '/myfont-webfont.eot?#iefix'
loaderUtils.interpolateName(loaderContext, '[path][name].[ext][query]&[hash]', { content: ... });
// => './myfont-webfont.eot?#iefix9473fdd0d880a43c21b7778d34872157'
```
