### ISSUE TITLE
Same base name will cause big problems!

### ISSUE THREAD

**Issue by mycoin** [webpack/loader-utils#41]
my webpack.config.js looks like: 

``` javascript
{
    test: /\.(png|jpg|gif)$/,
    loader: 'file-loader?name=assets/img/[name].[ext]'
}
```

If I do not interfere the file name, just like `name=assets/img/[name].[ext]` without hash, It may cause big problems.

``` css
body {
    background: url(~assets/image/bg.jpg);
}
.loading {
    background: url(~assets/bg.jpg);
}
```

After I built the project, there was only one file named `bg.jpg` in the folder `assets/img/`!

Thx
